/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as CostRouteImport } from './routes/cost'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PersonaRouteImport } from './routes/persona'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsShowIdRouteImport } from './routes/reports.$showId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaRoute = PersonaRouteImport.update({
  id: '/persona',
  path: '/persona',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsShowIdRoute = ReportsShowIdRouteImport.update({
  id: '/reports/$showId',
  path: '/reports/$showId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/analytics': typeof AnalyticsRoute
  '/catalog': typeof CatalogRoute
  '/console': typeof ConsoleRoute
  '/cost': typeof CostRoute
  '/drafts': typeof DraftsRoute
  '/login': typeof LoginRoute
  '/persona': typeof PersonaRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shows': typeof ShowsRoute
  '/terms': typeof TermsRoute
  '/reports/$showId': typeof ReportsShowIdRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/analytics': typeof AnalyticsRoute
  '/catalog': typeof CatalogRoute
  '/console': typeof ConsoleRoute
  '/cost': typeof CostRoute
  '/drafts': typeof DraftsRoute
  '/login': typeof LoginRoute
  '/persona': typeof PersonaRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shows': typeof ShowsRoute
  '/terms': typeof TermsRoute
  '/reports/$showId': typeof ReportsShowIdRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/analytics': typeof AnalyticsRoute
  '/catalog': typeof CatalogRoute
  '/console': typeof ConsoleRoute
  '/cost': typeof CostRoute
  '/drafts': typeof DraftsRoute
  '/login': typeof LoginRoute
  '/persona': typeof PersonaRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shows': typeof ShowsRoute
  '/terms': typeof TermsRoute
  '/reports/$showId': typeof ReportsShowIdRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/analytics'
    | '/catalog'
    | '/console'
    | '/cost'
    | '/drafts'
    | '/login'
    | '/persona'
    | '/privacy'
    | '/register'
    | '/rooms'
    | '/settings'
    | '/setup'
    | '/shows'
    | '/terms'
    | '/reports/$showId'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/analytics'
    | '/catalog'
    | '/console'
    | '/cost'
    | '/drafts'
    | '/login'
    | '/persona'
    | '/privacy'
    | '/register'
    | '/rooms'
    | '/settings'
    | '/setup'
    | '/shows'
    | '/terms'
    | '/reports/$showId'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/analytics'
    | '/catalog'
    | '/console'
    | '/cost'
    | '/drafts'
    | '/login'
    | '/persona'
    | '/privacy'
    | '/register'
    | '/rooms'
    | '/settings'
    | '/setup'
    | '/shows'
    | '/terms'
    | '/reports/$showId'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CatalogRoute: typeof CatalogRoute
  ConsoleRoute: typeof ConsoleRoute
  CostRoute: typeof CostRoute
  DraftsRoute: typeof DraftsRoute
  LoginRoute: typeof LoginRoute
  PersonaRoute: typeof PersonaRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  RoomsRoute: typeof RoomsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ShowsRoute: typeof ShowsRoute
  TermsRoute: typeof TermsRoute
  ReportsShowIdRoute: typeof ReportsShowIdRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona': {
      id: '/persona'
      path: '/persona'
      fullPath: '/persona'
      preLoaderRoute: typeof PersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$showId': {
      id: '/reports/$showId'
      path: '/reports/$showId'
      fullPath: '/reports/$showId'
      preLoaderRoute: typeof ReportsShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AnalyticsRoute: AnalyticsRoute,
  CatalogRoute: CatalogRoute,
  ConsoleRoute: ConsoleRoute,
  CostRoute: CostRoute,
  DraftsRoute: DraftsRoute,
  LoginRoute: LoginRoute,
  PersonaRoute: PersonaRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  RoomsRoute: RoomsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ShowsRoute: ShowsRoute,
  TermsRoute: TermsRoute,
  ReportsShowIdRoute: ReportsShowIdRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
